name: Terraform Module

on:
  workflow_call:
    inputs:
      working_directory:
        description: Path to the Terraform module root.
        required: true
        type: string
      environment:
        description: Environment name used for backend/vars, approvals and role resolution.
        required: true
        type: string
      action:
        description: Which action to perform (plan or apply)
        required: false
        type: string
        default: apply
      role_arn:
        description: Optional AWS role ARN to assume (overrides default constructed ARN or secret)
        required: false
        type: string
  workflow_dispatch:
    inputs:
      working_directory:
        description: Path to the Terraform module root.
        required: true
        default: "."
      environment:
        description: Environment name (drives backend/vars/plan/approval/role)
        required: true
        default: "prod"
      action:
        description: Which action to perform (plan, apply, destroy)
        required: true
        default: apply
        type: choice
        options:
          - plan
          - apply
          - destroy
      role_arn:
        description: Optional AWS role ARN to assume (overrides default constructed ARN or secret)
        required: false

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-${{ inputs.working_directory }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  plan:
    name: Plan
    if: ${{ inputs.action != 'destroy' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VERSION: '1.8.5'
      AWS_REGION: eu-west-1
      TF_ENVIRONMENT: ${{ inputs.environment }}
      TF_DIR: ${{ inputs.working_directory }}
      TF_VAR_maptiler_api_key: ${{ secrets.TF_MAPTILER_API_KEY || "" }}
      TF_VAR_here_api_key: ${{ secrets.TF_HERE_API_KEY || "" }}
      TF_VAR_database_password: ${{ secrets.TF_DATABASE_PASSWORD || "" }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    outputs:
      changed: ${{ steps.plan.outputs.plan_status == 'changes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Summarise inputs
        uses: GrantOps-Consulting/terraform-actions/.github/actions/print-run-context@main
        with:
          title: Terraform Module Workflow Context
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_role_arn: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          working_directory: ${{ inputs.working_directory }}
          var_file: env/${{ inputs.environment }}/${{ inputs.environment }}.tfvars
          plan_file: plan-${{ inputs.environment }}.tfplan
          terraform_version: 1.8.5
          action_type: ${{ inputs.action }}
          application: ${{ inputs.working_directory }}
          notes: "Reusable Terraform Module Workflow"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-setup@main
        with:
          environment: ${{ inputs.environment }}
          working_directory: ${{ inputs.working_directory }}

      - name: Terraform plan
        id: plan
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-plan@main
        with:
          working_directory: ${{ inputs.working_directory }}
          environment: ${{ inputs.environment }}

      # PR comment step removed per request

  plan-approval:
    name: Plan Approval Gate
    if: ${{ inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    needs: [plan]
    environment: ${{ format('{0}-deploy', inputs.environment) }}
    steps:
      - name: Await environment approval
        run: echo "Awaiting approval in environment '${{ format('{0}-deploy', inputs.environment) }}'"

  apply:
    name: Apply
    if: ${{ inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    needs: [plan, plan-approval]
    environment: ${{ inputs.environment }}
    env:
      TF_VERSION: '1.8.5'
      AWS_REGION: eu-west-1
      TF_ENVIRONMENT: ${{ inputs.environment }}
      TF_DIR: ${{ inputs.working_directory }}
      TF_VAR_maptiler_api_key: ${{ secrets.TF_MAPTILER_API_KEY || "" }}
      TF_VAR_here_api_key: ${{ secrets.TF_HERE_API_KEY || "" }}
      TF_VAR_database_password: ${{ secrets.TF_DATABASE_PASSWORD || "" }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-setup@main
        with:
          environment: ${{ inputs.environment }}
          working_directory: ${{ inputs.working_directory }}

      - name: Terraform apply
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-apply@main
        with:
          working_directory: ${{ inputs.working_directory }}
          environment: ${{ inputs.environment }}

  plan-destroy:
    name: Plan Destroy
    if: ${{ inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_maptiler_api_key: ${{ secrets.TF_MAPTILER_API_KEY || "" }}
      TF_VAR_here_api_key: ${{ secrets.TF_HERE_API_KEY || "" }}
      TF_VAR_database_password: ${{ secrets.TF_DATABASE_PASSWORD || "" }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Summarise inputs
        uses: GrantOps-Consulting/terraform-actions/.github/actions/print-run-context@main
        with:
          title: Terraform Module Workflow Context
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_role_arn: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          working_directory: ${{ inputs.working_directory }}
          var_file: env/${{ inputs.environment }}/${{ inputs.environment }}.tfvars
          plan_file: destroy-plan-${{ inputs.environment }}.tfplan
          terraform_version: 1.8.5
          action_type: ${{ inputs.action }}
          application: ${{ inputs.working_directory }}
          notes: "Reusable Terraform Module Workflow"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-setup@main
        with:
          environment: ${{ inputs.environment }}
          working_directory: ${{ inputs.working_directory }}

      - name: Terraform plan (destroy)
        id: destroy_plan
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-plan-destroy@main
        with:
          working_directory: ${{ inputs.working_directory }}
          environment: ${{ inputs.environment }}

  destroy-approval:
    name: Destroy Approval Gate
    if: ${{ inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    needs: [plan-destroy]
    environment: ${{ format('{0}-deploy', inputs.environment) }}
    steps:
      - name: Await environment approval
        run: echo "Awaiting approval in environment '${{ format('{0}-deploy', inputs.environment) }}'"

  destroy:
    name: Destroy
    if: ${{ inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    needs: [plan-destroy, destroy-approval]
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_maptiler_api_key: ${{ secrets.TF_MAPTILER_API_KEY || "" }}
      TF_VAR_here_api_key: ${{ secrets.TF_HERE_API_KEY || "" }}
      TF_VAR_database_password: ${{ secrets.TF_DATABASE_PASSWORD || "" }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn || secrets.AWS_TERRAFORM_ROLE_ARN || format('arn:aws:iam::%s:role/terraform-infrastructure-role-%s', vars.AWS_ACCOUNT_ID, inputs.environment) }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-setup@main
        with:
          environment: ${{ inputs.environment }}
          working_directory: ${{ inputs.working_directory }}

      - name: Terraform destroy
        uses: GrantOps-Consulting/terraform-actions/.github/actions/terraform-destroy@main
        with:
          working_directory: ${{ inputs.working_directory }}
          environment: ${{ inputs.environment }}
